# fly.toml app configuration file generated for portfolio-final-api on 2023-07-03T08:36:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-final-api"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
